### ISSUE TITLE
RequestStatus not working

### ISSUE THREAD

**Issue by FloMaetschke** [lifeemotions/knx.net#12]
I am using the Routing approach and i am not able to request a status.

Sending, Eventing works fine. But when i do a _connection.RequestStatus("1/2/3/");  the status event is not fired. just nothing happens.
any idea what might be wrong?

When i do switch on the lamp the status ga is updated and i do receive this update through the "Event" - event successfully.

**Comment by TiagoOliveiraMarques** [comment]
In the parameters of the actuator which is controlling the lamp, do you have any "status report" option, or something similar, enabled?

**Comment by FloMaetschke** [comment]
I am using MDTs AKK-1616.02 switch actuators: http://www.mdt.de/EN_Switch_Actuators_AKK.html 
They have a several object functions for each channel: right now i am using switching and actual status of a channel.

I want to read the status with knx.net with RequestStatus method.

ETS5 says: on the ga "Light1 status" type: 1.001
The mdt switch actuator object function  "status" has the following flags enabled:
Communication,
Read,
Transmit 

Its assigned to the ga and already working with my switch's led lamps.

Any Idea?

**Comment by FloMaetschke** [comment]
using your debug flag this is what happens:

1/1/42 is the ga for switching, 1/4/42 the ga for the actual status.

i do request status for 1/4/42



--------------------------------------------------------------------------------
---------------------
29-00-AC-F0-00-00-0C-2A-01-00-00
Event Header Length: 6
Event Protocol Version: 10
Event Service Type: 0x0530
Event Total Length: 17
Event Message Code: 29
Event Aditional Info Length: 0
Event Control Field 1: 10101100
Event Control Field 2: 11110000
Event Source Address: 0.0.0
Event Destination Address: 1/4/42
Event Data Length: 1
Event APDU: 0x0000
Event Data:
--------------------------------------------------------------------------------
---------------------
--------------------------------------------------------------------------------
---------------------
29-00-AC-F0-00-00-0C-2A-01-00-00
Event Header Length: 6
Event Protocol Version: 10
Event Service Type: 0x0530
Event Total Length: 17
Event Message Code: 29
Event Aditional Info Length: 0
Event Control Field 1: 10101100
Event Control Field 2: 11110000
Event Source Address: 0.0.0
Event Destination Address: 1/4/42
Event Data Length: 1
Event APDU: 0x0000
Event Data:
--------------------------------------------------------------------------------
---------------------
--------------------------------------------------------------------------------
---------------------
29-00-BC-F0-11-04-0C-2A-01-00-41
Event Header Length: 6
Event Protocol Version: 10
Event Service Type: 0x0530
Event Total Length: 17
Event Message Code: 29
Event Aditional Info Length: 0
Event Control Field 1: 10111100
Event Control Field 2: 11110000
Event Source Address: 1.1.4
Event Destination Address: 1/4/42
Event Data Length: 1
Event APDU: 0x0041
Event Data: ☺
--------------------------------------------------------------------------------

**Comment by FloMaetschke** [comment]
Oh man! 
I could knock my head on the wall....

Everything is working fine.

It was my fault.
            _connection.KnxEventDelegate += Event;
       _connection.KnxStatusDelegate += Status;  <--- this was missing in my code.. sorry
