### ISSUE TITLE
RequestStatus without delegate

### ISSUE THREAD

**Issue by denneboomyo** [lifeemotions/knx.net#26]
Hi,

I was wondering if there is any way to receive the status of a device directly to a variable, like this:
string state = connection.RequestStatus("0/0/1");

Thanks

**Comment by abelsilva** [comment]
Hi

No, KNX protocol is asynchronous.
Although you can implement a wrapper function that would lock until the value expected is received.

Thanks

**Comment by denneboomyo** [comment]
Okay, thanks. You can close the issue.
