### ISSUE TITLE
Is this repo completed/stable?

### ISSUE THREAD

**Issue by bitver** [lifeemotions/knx.net#29]
For example, I mean this: https://github.com/lifeemotions/knx.net/blob/master/src/KNXLib/KnxReceiverTunneling.cs#L178-L186
`knxDatagram` is never used, are you going to finish writing or just forgot to remove this variable?

**Comment by abelsilva** [comment]
I don't understand, the ```knxDatagram``` is used in 3 more places just after being declared (in same method).
Two times to log an info message.
One time to declare the channel ID (without this one the connection wouldn't work).

Yes, the comparisons could be done directly using the byte array, but it wouldn't be easy to read

Also, if the header is needed for something else, it is already built.
