### ISSUE TITLE
Do I have to keep alive a long knx tunneling connection?

### ISSUE THREAD

**Issue by mronnlun** [lifeemotions/knx.net#30]
I'm creating a window service that will monitor knx events.

Should I do something manually to keep alive the connection, like requesting a status every minute, or isn't it needed?

**Comment by abelsilva** [comment]
For any type of connection you don't need to do anything

KNX Routing doesn't have state
KNX Tunneling (the one you're using) already has it's own keep alive (implemented in knx.net)

If you still want to be sure you can always request the state of the devices you want to monitor each X secs/mins

**Comment by abelsilva** [comment]
https://github.com/lifeemotions/knx.net/blob/master/src/KNXLib/KnxConnectionTunneling.cs#L203

Method StateRequest is called every 60s to send the 'keep alive'

**Comment by mronnlun** [comment]
Thanks for the info. I have now had a connection up for a week without problems.

When I look at my own logs, the keep alive polling address seems to be 1/1/1 because that is regularly shown in my logs. Maybe that address could be specified in the constructor to some defined value that I could then filter out.
