### ISSUE TITLE
Manually set 

### ISSUE THREAD

**Issue by ThomasLammens** [lifeemotions/knx.net#34]
Dear,

We are now getting an "event" for the correct address when we execute a "requestStatus" call. How do we go about receiving an event when a switch is set manually ?

Kind regards,
Thomas

**Comment by abelsilva** [comment]
what do you mean by `when a switch is set manually`?

**Comment by ThomasLammens** [comment]
Dear Abel,
When we use a button to manually switch the actor, we want to read the status of the actor, this is (as far as we know) now not possible. We can read the status of an actor switched by the software we are developing but when it is switched manually there is no readable status change.

kind regards,
Thomas

**Comment by abelsilva** [comment]
Check the README

Requesting status

**Comment by abelsilva** [comment]
If you to be notified you just need to subscribe the delegates

If KNX is not sending the events, you need to configure the actuators to send them

**Comment by ThomasLammens** [comment]
Hey Abel,

Thanks again for the help, we managed to find our problem and found a fix for it. 

Kind regards,
Thomas
